#!/bin/bash

#PBS -N D2_MPI

#PBS -o ./outputMPI.o
#PBS -e ./outputMPI.e

#PBS -q short_cpuQ

#PBS -l walltime=0:30:00

#PBS -l select=1:ncpus=32:mpiprocs=32:mem=1gb

module load gcc91
module load mpich-3.2.1--gcc-9.1.0

g++() {
    g++-9.1.0 "$@"
}

g++ --version


# Select the working directory (change this line)
cd /home/directory 

mpicxx -o C d2MPI.cpp

mpirun -np 1 ./C
mpirun -np 2 ./C
mpirun -np 4 ./C
mpirun -np 8 ./C
mpirun -np 16 ./C
mpirun -np 32 ./C